openai_clients:
  - name: "deepseek_cloud"
    # api_key: "sk-11f4a74a7ca34dd3a88721935947bc57"
    api_key: "sk-cfcc988838f84e4482e77fa92eb8a597"
    base_url: "https://api.deepseek.com"
    model_match:
      type: "keyword"
      value: ["deepseek"]
    priority: 2
    max_tokens: 8192

  - name: "qwenvl"
    base_url: "http://192.168.9.120:1025/v1"
    model_match:
      type: "keyword"
      value: ["Qwen3-VL-235B-A22B-Instruct"]
    priority: 1
    fallback: "Qwen3.5-397B-A17B"

  - name: "qwen35"
    base_url: "http://192.168.9.120:1025/v1"
    model_match:
      type: "keyword"
      value: ["Qwen3.5-397B-A17B"]
    priority: 1

  - name: "minimax_loacal"
    base_url: "http://192.168.10.25:8000/v1"
    api_key: "xk-0pRR5I8xQqEW3Y4TEtyNynLBvFpwBEVo"
    model_match:
      type: "keyword"
      value: ["MiniMax-M2.1"]
    priority: 1

  - name: "minimax2_loacal"
    base_url: "http://192.168.10.23:1025/v1"
    api_key: "xk-0pRR5I8xQqEW3Y4TEtyNynLBvFpwBEVo"
    model_match:
      type: "keyword"
      value: ["MiniMax-M2.5"]
    priority: 1

  - name: "glm_loacal"
    base_url: "http://192.168.9.122:1025/v1"
    model_match:
      type: "keyword"
      value: ["GLM-5"]
    priority: 1

  - name: "Mobius"
    base_url: "http://192.168.10.121:2525/v1"
    model_match:
      type: "exact"
      value: ["Mobius-r6-12B-chat", "xiaoke", "xiaoke-chat"]
    priority: 4 
    # stop: ["\n\nUser:", "\n\nAssistant:", "\n\nObservation:", "[PAD65531]"]

  - name: "Mobius-cot"
    base_url: "http://192.168.10.121:2525/v1"
    model_match:
      type: "exact"
      value: ["Mobius-r6-12B-cot", "xiaoke-cot"]
    priority: 4
    special_prefix: "<think>"  # 特殊模型标记
    # stop: ["\n\nUser:", "\n\nAssistant:", "\n\nObservation:", "[PAD65531]"]


  - name: "Xiaoke-coe"
    base_url: "http://192.168.10.123:8000/v1"
    model_match:
      type: "exact"
      value: ["xiaoke-coe"]
    priority: 4
    # stop: ["\n\nUser:", "\n\nAssistant:", "\n\nObservation:", "[PAD65531]"]

  
  # - name: "RWKV7"
  #   base_url: "http://192.168.10.121:9998/v1"
  #   model_match:
  #     type: "exact"
  #     value: ["RWKV-v7-G0-7.2B", "RWKV-v7-G0a3-7.2B"]
  #   priority: 4
  #   stop: ["\n\nUser:", "\n\nAssistant:", "\n\nObservation:", "User:", "Assistant:", "Observation:", "\n\nUser"]

  # - name: "RWKV7-Think"
  #   base_url: "http://192.168.10.121:9998/v1"
  #   model_match:
  #     type: "exact"
  #     value: ["RWKV-v7-G0-7.2B:thinking", "RWKV-v7-G0-7.2B-think", "RWKV-v7-G0a3-7.2B:thinking", "RWKV-v7-G0a3-7.2B-think"]
  #   priority: 4
  #   special_prefix: "<think>"  # 特殊模型标记
  #   stop: ["\n\nUser:", "\n\nAssistant:", "\n\nObservation:", "User:", "Assistant:", "Observation:", "\n\nUser"]

  # - name: "RWKV13"
  #   base_url: "http://192.168.10.121:9999/v1"
  #   model_match:
  #     type: "exact"
  #     value: ["RWKV-v7-G0-13.3B","RWKV-v7-G0b-13.3B","rwkv"]
  #   priority: 4
  #   stop: ["\n\nUser:", "\n\nAssistant:", "\n\nObservation:", "User:", "Assistant:", "Observation:", "\n\nUser"]

  # - name: "RWKV13-Think"
  #   base_url: "http://192.168.10.121:9999/v1"
  #   model_match:
  #     type: "exact"
  #     value: ["RWKV-v7-G0-13.3B:thinking", "RWKV-v7-G0-13.3B-think","RWKV-v7-G0b-13.3B:thinking", "RWKV-v7-G0b-13.3B-think"]
  #   priority: 4
  #   special_prefix: "<think>"  # 特殊模型标记
  #   stop: ["\n\nUser:", "\n\nAssistant:", "\n\nObservation:", "User:", "Assistant:", "Observation:", "\n\nUser"]

  
  # - name: "RWKV30"
  #   base_url: "http://192.168.9.31:8000/v1"
  #   model_match:
  #     type: "exact"
  #     value: ["Mobius-r7-base-30B"]
  #   priority: 4
  #   stop: ["\n\nUser:", "\n\nAssistant:", "\n\nObservation:", "User:", "Assistant:", "Observation:", "\n\nUser"]

  # - name: "RWKV30-Think"
  #   base_url: "http://192.168.9.31:8000/v1"
  #   model_match:
  #     type: "exact"
  #     value: ["Mobius-r7-base-30B:thinking", "Mobius-r7-base-30B-think"]
  #   priority: 4
  #   special_prefix: "<think>"  # 特殊模型标记
  #   stop: ["\n\nUser:", "\n\nAssistant:", "\n\nObservation:", "User:", "Assistant:", "Observation:", "\n\nUser"]
