# .github/workflows/release.yml

name: Release

on:
  push:
    branches:
      - main # 或者您的主分支

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write # 必须有写入权限来创建 Release
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # 必须获取所有历史记录才能正确计数

      # 新的逻辑：获取 commit 总数来生成版本号
      - name: Get version from commit count
        id: version
        run: |
          commit_count=$(git rev-list --count HEAD)
          echo "tag=b${commit_count}" >> $GITHUB_OUTPUT

      - name: Get latest commit message
        id: commit
        run: echo "message=$(git log -1 --pretty=%s)" >> $GITHUB_OUTPUT

      - name: Create Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          # 使用上面步骤生成的 tag
          tag_name: ${{ steps.version.outputs.tag }}
          release_name: Release ${{ steps.version.outputs.tag }}
          body: ${{ steps.commit.outputs.message }}
          draft: false
          prerelease: false